baseURL = 'https://dozingunicorn.github.io/'
locale = 'en-us'
theme = 'beautifulhugo'
publishDir = 'docs'

[security]
enableInlineShortcodes = true

# [services]
#   [services.googleAnalytics]
#     id = "G-xxxxxxxx"

[params]
homeTitle = "DozingUnicorn"
subtitle = "High Effort - Silly Subjects"
mainSections = ["post", "posts"]
logo = "/img/android-chrome-512x512.png"
favicon = "/img/favicon.ico"
dateFormat = "January 2, 2006"
colorScheme = "auto"
readingTime = true
socialShare = false
showRelatedPosts = true
rss = true
headerImgStyle = "big"
#disableFigureOverride = true

[pagination]
pagerSize = 5

[params.search]
provider = "fuse"

[params.author]
name = "John Purcell"
website = "dozingunicorn.com"
instagram = "dozingunicorn"
telegram = "DozingUnicorn"
bluesky = "dozingunicorn.bsky.social" # BROKEN

[markup.highlight]
noClasses = false

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true